<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 */

// Register The Composer Auto Loader
require __DIR__.'/../vendor/autoload.php';

// Load application settings.
require_once __DIR__ . '/../config/application.php';

// Bootstrap WordPress.
require_once ABSPATH . 'wp-settings.php';
